CONNECT LOGISTICS_APP/Logistics_2026_TestOnly@//localhost:1521/FREEPDB1

CREATE TABLE REGION_DICT (
  REGION_CODE VARCHAR2(12) PRIMARY KEY, REGION_NAME VARCHAR2(60) NOT NULL,
  PARENT_CODE VARCHAR2(12), LV NUMBER(2), C01 VARCHAR2(30)
);
COMMENT ON TABLE REGION_DICT IS '行政区划及运营区域字典';
COMMENT ON COLUMN REGION_DICT.C01 IS '历史系统保留属性，可能为空';

CREATE TABLE BRANCH (
  BRANCH_ID NUMBER PRIMARY KEY, BRANCH_CODE VARCHAR2(12) UNIQUE NOT NULL,
  BRANCH_NAME VARCHAR2(100) NOT NULL, REGION_CODE VARCHAR2(12), ADDRESS VARCHAR2(200),
  MANAGER_NAME VARCHAR2(40), PHONE VARCHAR2(30), ACTIVE_FLAG CHAR(1) DEFAULT 'Y', OPEN_DATE DATE,
  CONSTRAINT FK_BRANCH_REGION FOREIGN KEY (REGION_CODE) REFERENCES REGION_DICT(REGION_CODE)
);

CREATE TABLE CUSTOMER (
  CUSTOMER_ID NUMBER PRIMARY KEY, CUSTOMER_NO VARCHAR2(20) UNIQUE NOT NULL,
  CUSTOMER_NAME VARCHAR2(120) NOT NULL, CUSTOMER_TYPE VARCHAR2(12), CREDIT_LEVEL CHAR(1),
  CONTACT_NAME VARCHAR2(40), CONTACT_PHONE VARCHAR2(30), BILLING_CYCLE VARCHAR2(10),
  HOME_BRANCH_ID NUMBER, CREATED_AT TIMESTAMP, REMARK VARCHAR2(300),
  CONSTRAINT FK_CUST_BRANCH FOREIGN KEY (HOME_BRANCH_ID) REFERENCES BRANCH(BRANCH_ID)
);
COMMENT ON TABLE CUSTOMER IS '物流客户主数据';
COMMENT ON COLUMN CUSTOMER.CREDIT_LEVEL IS 'A-D，A为最高';

CREATE TABLE DRIVER (
  ID NUMBER PRIMARY KEY, XM VARCHAR2(40), SJ VARCHAR2(30), SFZ VARCHAR2(24),
  WD_DM VARCHAR2(12), ZT CHAR(1), RQ DATE, LIC_TYPE VARCHAR2(8)
);

CREATE TABLE VEHICLE (
  VEHICLE_ID NUMBER PRIMARY KEY, PLATE_NO VARCHAR2(16) UNIQUE NOT NULL,
  VEHICLE_TYPE VARCHAR2(20), CAPACITY_KG NUMBER(12,2), CAPACITY_M3 NUMBER(8,2),
  OWNER_TYPE CHAR(1), BRANCH_CODE VARCHAR2(12), STATUS_CODE VARCHAR2(10),
  PURCHASE_DATE DATE, NEXT_MAINT_DATE DATE
);

CREATE TABLE ROUTE_MASTER (
  ROUTE_ID NUMBER PRIMARY KEY, LINE_CD VARCHAR2(16) UNIQUE, ORIGIN_BRANCH_ID NUMBER,
  DEST_BRANCH_ID NUMBER, DIST_KM NUMBER(8,1), STD_HOURS NUMBER(6,1), ZT CHAR(1), C02 VARCHAR2(60),
  CONSTRAINT FK_ROUTE_O FOREIGN KEY (ORIGIN_BRANCH_ID) REFERENCES BRANCH(BRANCH_ID),
  CONSTRAINT FK_ROUTE_D FOREIGN KEY (DEST_BRANCH_ID) REFERENCES BRANCH(BRANCH_ID)
);

CREATE TABLE T_YD01 (
  ID NUMBER PRIMARY KEY, YD_H VARCHAR2(24) UNIQUE NOT NULL, KH_BH VARCHAR2(20),
  F_WD VARCHAR2(12), D_WD VARCHAR2(12), RQ DATE, SJ TIMESTAMP, ZL NUMBER(12,2),
  JS NUMBER(8), JE NUMBER(14,2), ZT VARCHAR2(8), YSFS VARCHAR2(8), C01 VARCHAR2(80),
  CREATED_BY VARCHAR2(30)
);
COMMENT ON COLUMN T_YD01.YD_H IS '运单号码';
COMMENT ON COLUMN T_YD01.ZT IS '运单状态编码';

CREATE TABLE T_YD02 (
  MX_ID NUMBER PRIMARY KEY, YD_H VARCHAR2(24) NOT NULL, XH NUMBER(5), PM VARCHAR2(80),
  SL NUMBER(10), ZL NUMBER(12,2), TJ NUMBER(10,3), BZ VARCHAR2(120), HPLX VARCHAR2(10)
);

CREATE TABLE PACKAGE_ITEM (
  PACKAGE_ID NUMBER PRIMARY KEY, PACKAGE_NO VARCHAR2(28) UNIQUE NOT NULL,
  WAYBILL_NO VARCHAR2(24), SEQ_NO NUMBER(5), LENGTH_CM NUMBER(8,2), WIDTH_CM NUMBER(8,2),
  HEIGHT_CM NUMBER(8,2), WEIGHT_KG NUMBER(10,2), BARCODE_STATUS VARCHAR2(12), CREATED_TIME TIMESTAMP
);

CREATE TABLE DISPATCH_TASK (
  TASK_ID NUMBER PRIMARY KEY, CC VARCHAR2(20), LINE_CD VARCHAR2(16), VEHICLE_ID NUMBER,
  DRIVER_ID NUMBER, PLAN_ST TIMESTAMP, ACT_ST TIMESTAMP, PLAN_ET TIMESTAMP, ACT_ET TIMESTAMP,
  ZT VARCHAR2(8), LOAD_RATE NUMBER(5,2), C01 VARCHAR2(100),
  CONSTRAINT FK_TASK_V FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID),
  CONSTRAINT FK_TASK_D FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER(ID)
);

CREATE TABLE TASK_WAYBILL (
  TASK_ID NUMBER NOT NULL, YD_H VARCHAR2(24) NOT NULL, SX NUMBER(6), LOAD_TM TIMESTAMP,
  UNLOAD_TM TIMESTAMP, PRIMARY KEY(TASK_ID, YD_H),
  CONSTRAINT FK_TW_TASK FOREIGN KEY (TASK_ID) REFERENCES DISPATCH_TASK(TASK_ID)
);

CREATE TABLE PS_GJ (
  GJ_ID NUMBER PRIMARY KEY, YD_H VARCHAR2(24), SJ TIMESTAMP, WD_DM VARCHAR2(12),
  CZ_DM VARCHAR2(8), CZR VARCHAR2(30), GPS_X NUMBER(12,6), GPS_Y NUMBER(12,6), BZ VARCHAR2(160)
);

CREATE TABLE T_X9 (
  XID NUMBER PRIMARY KEY, YD_H VARCHAR2(24), LX VARCHAR2(8), RQ TIMESTAMP,
  ZT CHAR(1), ZR VARCHAR2(30), C01 VARCHAR2(200), C02 NUMBER(12,2), CLOSE_TM TIMESTAMP
);

CREATE TABLE DELIVERY_PROOF (
  PROOF_ID NUMBER PRIMARY KEY, WAYBILL_NO VARCHAR2(24), SIGNER_NAME VARCHAR2(40),
  SIGN_TIME TIMESTAMP, SIGN_TYPE VARCHAR2(12), IMAGE_REF VARCHAR2(160), LATITUDE NUMBER(12,6),
  LONGITUDE NUMBER(12,6), NOTE VARCHAR2(200)
);
COMMENT ON TABLE DELIVERY_PROOF IS '签收及电子回单记录，图片字段仅保存本地模拟引用';

CREATE TABLE FY_JS (
  JS_ID NUMBER PRIMARY KEY, YD_H VARCHAR2(24), KH_BH VARCHAR2(20), FYLX VARCHAR2(10),
  JE NUMBER(14,2), BZ NUMBER(14,2), SJ DATE, ZT CHAR(1), FP_H VARCHAR2(30), C01 VARCHAR2(50)
);

CREATE TABLE CK_JL (
  ID NUMBER PRIMARY KEY, WD_DM VARCHAR2(12), YD_H VARCHAR2(24), CKW VARCHAR2(16),
  RQ TIMESTAMP, CZR VARCHAR2(30), LX CHAR(1), SL NUMBER(8), C01 VARCHAR2(80)
);

CREATE INDEX IX_YD01_KH_RQ ON T_YD01(KH_BH, RQ);
CREATE INDEX IX_YD02_YDH ON T_YD02(YD_H);
CREATE INDEX IX_GJ_YDH_SJ ON PS_GJ(YD_H, SJ);
CREATE INDEX IX_X9_YDH ON T_X9(YD_H);
CREATE INDEX IX_FY_KH_SJ ON FY_JS(KH_BH, SJ);
CREATE INDEX IX_PKG_WB ON PACKAGE_ITEM(WAYBILL_NO);

COMMIT;
