"""add document content hash

Revision ID: d281df2f2167
Revises: bfb3fc01fe72
Create Date: 2026-07-15 23:16:13.066127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd281df2f2167'
down_revision: Union[str, Sequence[str], None] = 'bfb3fc01fe72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_documents_knowledge_base_content_hash', 'documents', ['knowledge_base_id', 'content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_documents_knowledge_base_content_hash', 'documents', type_='unique')
    op.drop_column('documents', 'content_hash')
    # ### end Alembic commands ###
